### PR TITLE
Improvements for search

### PR DESCRIPTION
**Pull request by jvega190**
- Add support for exact matches using quotes
- Add support for field boosting to improve search results

https://github.com/craftercms/craftercms/issues/3160

Modify all blueprints to comment out the example.com email address (https://github.com/craftercms/craftercms/issues/4833)

### CODE REVIEW

**Review by rart — CHANGES_REQUESTED** [review]
Fix indentation of xml changes

**Comment by jvega190** [comment]
@rart this is ready for merge

**Review by rart — APPROVED** [review]
Verified version upgrade

@jvega190 changes for next?

**Comment by jvega190** [comment]
Already done/merged in https://github.com/craftercms/video-center-blueprint/commit/c9436f9b8fb56ea7dd3109424a8fc0a2e7f412d4

**Pull request merged**
