### PR TITLE
[5263][next] Add pagination to List component

### PR DESCRIPTION
**Pull request by phuongnq**
* https://github.com/craftercms/craftercms/issues/5263
* Update UI config to use `Git`

### CODE REVIEW

**Review by rart — COMMENTED** [review]
I see some changes on the yarn.lock, but no changes on package.json. Please confirm nothing was left behind at commit time.

**Comment by phuongnq** [comment]
@rart The files are up to date.
This BP originally works with Node `v10.24.1` but since we are using XB with `js-cookie@3.0.1` it requires a later version:
```
error js-cookie@3.0.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
```

As soon as I switch to using Node later version (v16.14.2), there is an error with the optional dependency `microtime@^2.1.0`:

```
warning Error running install script for optional dependency: "/home/pnguyen/Downloads/video-center-blueprint/sources/app/node_modules/microtime: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/pnguyen/Downloads/video-center-blueprint/sources/app/node_modules/microtime
Output:
prebuild-install WARN install No prebuilt binaries found (target=16.14.2 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.2 | linux | x64
gyp info find Python using Python version 3.8.10 found at \"/usr/bin/python3\"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/pnguyen/.nodebrew/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pnguyen/Downloads/video-center-blueprint/sources/app/node_modules/microtime/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pnguyen/.nodebrew/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pnguyen/.cache/node-gyp/16.14.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pnguyen/.cache/node-gyp/16.14.2',
gyp info spawn args   '-Dnode_gyp_dir=/home/pnguyen/.nodebrew/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pnguyen/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pnguyen/Downloads/video-center-blueprint/sources/app/node_modules/microtime',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pnguyen/Downloads/video-center-blueprint/sources/app/node_modules/microtime/build'
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../node_modules/nan/nan_converters.h:67,
                 from ../node_modules/nan/nan.h:222,
                 from ../src/microtime.cc:9:
../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../node_modules/nan/nan_converters_43_inl.h:18:49: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \\\n      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                 |
      |                                                 v8::Local<v8::Context>
../node_modules/nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
   22 | X(Boolean)
      | ^
In file included from /home/pnguyen/.cache/node-gyp/16.14.2/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3086:37: note:   initializing argument 1 of ‘v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const’
 3086 |   Local<Boolean> ToBoolean(Isolate* isolate) const;
      |                            ~~~~~~~~~^~~~~~~
In file included from ../node_modules/nan/nan_converters.h:67,
                 from ../node_modules/nan/nan.h:222,
                 from ../src/microtime.cc:9:
../node_modules/nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../node_modules/nan/nan_converters_43_inl.h:37:55: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \\\n      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                       |
      |                                                       v8::Local<v8::Context>
../node_modules/nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
   40 | X(bool, Boolean)
      | ^
In file included from /home/pnguyen/.cache/node-gyp/16.14.2/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3096:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 3096 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
In file included from ../node_modules/nan/nan_new.h:189,
                 from ../node_modules/nan/nan.h:223,
                 from ../src/microtime.cc:9:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../node_modules/nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
  356 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                     ^
In file included from /home/pnguyen/.cache/node-gyp/16.14.2/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:6196:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
 6196 |   static Local<Value> New(Isolate* isolate, Local<String> value);
      |                       ^~~
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:6196:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../node_modules/nan/nan_new.h:189,
                 from ../node_modules/nan/nan.h:223,
                 from ../src/microtime.cc:9:
../node_modules/nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before ‘>’ token
  356 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                          ^
../node_modules/nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ‘)’ token
  356 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                            ^
In file included from ../src/microtime.cc:9:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2232:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /usr/include/c++/9/cassert:44,
                 from /home/pnguyen/.cache/node-gyp/16.14.2/include/node/node_object_wrap.h:26,
                 from ../node_modules/nan/nan.h:55,
                 from ../src/microtime.cc:9:
../node_modules/nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../node_modules/nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
   24 |     assert(persistent().IsNearDeath());
      |                         ^~~~~~~~~~~
../node_modules/nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../node_modules/nan/nan_object_wrap.h:127:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  127 |     assert(wrap->handle_.IsNearDeath());
      |                          ^~~~~~~~~~~
../src/microtime.cc: In function ‘void NowStruct(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/microtime.cc:75:78: error: no matching function for call to ‘v8::Array::Set(Nan::imp::IntegerFactory<v8::Integer>::return_t, Nan::imp::FactoryBase<v8::Number>::return_t)’
   75 |   array->Set(Nan::New<v8::Integer>(0), Nan::New<v8::Number>((double)t.tv_sec));
      |                                                                              ^
In file included from /home/pnguyen/.cache/node-gyp/16.14.2/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3961 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3961:37: note:   candidate expects 3 arguments, 2 provided
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3964 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3964:37: note:   candidate expects 3 arguments, 2 provided
../src/microtime.cc:76:79: error: no matching function for call to ‘v8::Array::Set(Nan::imp::IntegerFactory<v8::Integer>::return_t, Nan::imp::FactoryBase<v8::Number>::return_t)’
   76 |   array->Set(Nan::New<v8::Integer>(1), Nan::New<v8::Number>((double)t.tv_usec));
      |                                                                               ^
In file included from /home/pnguyen/.cache/node-gyp/16.14.2/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/microtime.cc:9:
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3961 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3961:37: note:   candidate expects 3 arguments, 2 provided
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3964 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/v8.h:3964:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../node_modules/nan/nan.h:53,
                 from ../src/microtime.cc:9:
../src/microtime.cc: At global scope:
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/node.h:842:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  842 |       (node::addon_register_func) (regfunc),                          \\\n      |                                           ^
/home/pnguyen/.cache/node-gyp/16.14.2/include/node/node.h:876:3: note: in expansion of macro ‘NODE_MODULE_X’
  876 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/microtime.cc:95:1: note: in expansion of macro ‘NODE_MODULE’
   95 | NODE_MODULE(microtime, InitAll)
      | ^~~~~~~~~~~
make: *** [microtime.target.mk:113: Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory '/home/pnguyen/Downloads/video-center-blueprint/sources/app/node_modules/microtime/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pnguyen/.nodebrew/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.8.0-55-generic
gyp ERR! command \"/home/pnguyen/.nodebrew/node/v16.14.2/bin/node\" \"/home/pnguyen/.nodebrew/node/v16.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/pnguyen/Downloads/video-center-blueprint/sources/app/node_modules/microtime
```
The issue was that `microtime` version 2.1.0 does not have build-in for certain  architecture in this version that caused the error. They fixed this in 3.0.0: https://github.com/wadey/node-microtime/releases

Here is the dependency tree:

```
microtime@^2.1.0:
  version "2.1.9"
  resolved "https://registry.yarnpkg.com/microtime/-/microtime-2.1.9.tgz#f4073289599ef4dd1a673f2b1fe6f9c9502f784e"
  integrity sha512-p3ZEcEHs220fl7kZd+Z4NParEuwE6WR02tlQ8sDIOJyiRYfDofxTMJYNBi5ZTOHzyGObsZnPmvvFim9vuDMdOw==
  dependencies:
    bindings "^1.3.1"
    nan "2.12.x"
    prebuild-install "^5.2.2"
```

```
es-sifter@0.5.2:
  version "0.5.2"
  resolved "https://registry.yarnpkg.com/es-sifter/-/es-sifter-0.5.2.tgz#6a1404b185663dcf13789c515f6f691bc88043ad"
  integrity sha1-ahQEsYVmPc8TeJxRX29pG8iAQ60=
  dependencies:
    async "0.2.x"
    cardinal "0.4.x"
    csv-parse "^1.1.7"
    humanize "0.0.x"
    optimist "0.6.x"
  optionalDependencies:
    microtime "^2.1.0"
```

```
es-selectize@0.12.9:
  version "0.12.9"
  resolved "https://registry.yarnpkg.com/es-selectize/-/es-selectize-0.12.9.tgz#b78fbf240edae4a4ce58d9adfa940cccef6e487f"
  integrity sha1-t4+/JA7a5KTOWNmt+pQMzO9uSH8=
  dependencies:
    es-microplugin "0.0.4"
    es-sifter "0.5.2"

es-selectize@^0.12.9:
  version "0.12.10"
  resolved "https://registry.yarnpkg.com/es-selectize/-/es-selectize-0.12.10.tgz#303c66308bcf5f9948cf8aba7e3b3dbf0b5651b6"
  integrity sha512-sfUJ54hOoJA01x1XbABNTzTuah5iqVq/M3i0LJxmgLnc7NlaCIf4e2GilgzCBgFJCgz0or5LpRKck4sMBaGwww==
  dependencies:
    es-microplugin "0.0.4"
    es-sifter "0.5.2"
```

```
dash.js@^4.0.0:
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/dash.js/-/dash.js-4.0.0.tgz#a306a145ff2bb6d1d098c29fe5b7ee158208e8fd"
  integrity sha512-oQ6OZka7PB5rrv8Ewitv5PZ3k3ky9clEMWzeqI6Thpxm1jr3TVagRlJIWrOfAtA+bIliPH/RrFEjuZKiktZtkg==
  dependencies:
    akasha "^0.1.9"
    broken "^0.1.13"
    d3-array "1.2.0"
    d3-axis "1.0.7"
    d3-interpolate "1.1.5"
    d3-selection "1.1.0"
    d3-shape "1.2.0"
    d3-svg-legend "2.24.1"
    d3-tip "0.8.0-alpha.1"
    d3-transition "1.1.0"
    el-controls "1.1.7"
    el.js "^2.1.24"
    es-is "^3.3.10"
    es-raf "^3.3.1"
    es-selectize "^0.12.9"
    es-tween "^0.1.0"
    hanzo.js "^2.3.23"
    moment-timezone "0.5.13"
    randomcolor "0.5.2"
    referential "^0.5.23"
    riot-observable "3.0.0"
```

Updating `dash.js` is too much for this PR so IMO, we can update the `microtime` *optional dependency* version to 3.0.0.
At some point, we may need to upgrade all the dependencies for this repo.

**Comment by rart** [comment]
What mechanism did you use to apply  the yarn lock file changes & upgrading microtime?

**Comment by phuongnq** [comment]
Hi @rart 

I directly update the version in `yarn.lock` for this.

```
  optionalDependencies:
    microtime "^2.1.0"
```

=>

```
  optionalDependencies:
    microtime "^3.0.0"
```

But now, I have just noticed that I can build *without* optional dependencies with:

```
yarn --ignore-optional
```

So I used the above command to instance dependencies and build.
This seems to work as well so I removed the change for `yarn.lock`.

Or if you have other suggestions on how to build this please let me know. Just wondering how team build this before?

**Comment by rart** [comment]
Manipulating the yarn lock manually is not a great idea. Best bet would be `yarn upgrade-interactive` — or `yarn upgrade` but that can be a bit _aggressive_.

**Review by rart — APPROVED** [review]

**Pull request merged**
